#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

# shellcheck disable=SC1091
source "/etc/os-release"

print_columns "OS" "${NAME} ${VERSION:-}"
