#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

ips_v4=$(ip a | awk '/inet / && /global/ {split($2, arr, /\//); print arr[1]}')
IFS=$'\n' read -r -a ip4s <<< "${ips_v4}"

ips_v6=$(ip a | awk '/inet6 / && /global/ {split($2, arr, /\//); print arr[1]}')
IFS=$'\n' read -r -a ip6s <<< "${ips_v6}"

text4=$(print_wrap "${WIDTH}" "${ip4s[@]}")
text6=$(print_wrap "${WIDTH}" "${ip6s[@]}")

print_columns "IPv4 addresses" "${text4}"
print_columns "IPv6 addresses" "${text6}"
