#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

ips_v4=$(ip a | awk '/inet / && /global/ {split($2, arr, /\//); print arr[1]}')
IFS=$'\n' read -r -a ips <<< "${ips_v4}"

text=$(print_wrap "${WIDTH}" "${ips[@]}")

print_columns "IP addresses" "${text}"
