#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

cores="$(sensors | grep Core | awk '{printf "%s ", $3} {printf "%s %s %s\n", $6, $9, $12}' | tr -d '+°C,)')"

text=""
while IFS= read -r line; do
    IFS=" " read -r current high critical <<< "${line}"

    if [[ "${high}" == "${critical}" ]]; then
        high=$(bc -l <<< "${high} - 20")
    fi

    text+="$(print_color "${current}°C" "${current}" "${high}" "${critical}"), "
done <<< "${cores}"

print_columns "Temperatures" "${text::-2}"
