#!/usr/bin/env bash

set -euo pipefail
# shellcheck source=./framework.sh
source "${BASE_DIR}/framework.sh"

type smartctl > /dev/null 2>&1 || exit 1
# Check if the user can execute smartctl with sudo without any password
sudo -n smartctl --version > /dev/null 2>&1 || exit 1

# Disk list:
disks=$(lsblk | awk '($6=="disk") {print $1}')

statuses=()
for disk in $disks; do
    smart_test=$(sudo smartctl -H "/dev/$disk" 2>/dev/null | grep '^SMART overall\|^SMART Health Status' | rev | cut -d ' ' -f1 | rev)

    if [[ -z "$smart_test" ]]; then
        smart_test="unavailable"
    elif [[ "$smart_test" == 'PASSED' ]]; then
        smart_test="${CO}${smart_test}${CN}"
    else
        smart_test="${CE}${smart_test}${CN}"
    fi

    statuses+=("${disk} ${smart_test}")
done

text=$(print_wrap "${WIDTH}" "${statuses[@]}")

print_columns "S.M.A.R.T." "${text}"
